[package]
name = "tcpRust"
version = "0.1.0"
authors = ["Kenan Furkan Kaptan <kfk1998@gmail.com>"]
edition = "2021"

[dependencies]
tun-tap = "0.1.2"
etherparse = "0.8"
bitflags = "1.3.2"
nix = "0.13"

[lib]
name = "tcpRust"

[[bin]]
name = "tcpRust"